### ISSUE TITLE
Implement on Colab

### ISSUE THREAD

**Issue by SlimeVRX** [adobe-research/sunstage#2]
How to run code?

I just create a [Colab](https://colab.research.google.com/drive/1O03rYSutX1x3tgUPfA3iHTEztGcdgiqp?usp=sharing)

Have a bug
```
%cd /content/sunstage
!python train_s1.py
```

```
/content/sunstage
Traceback (most recent call last):
  File "/content/sunstage/train_s1.py", line 24, in <module>
    dataset = SunStageData(opt)
  File "/content/sunstage/sunstage_dataset.py", line 14, in __init__
    with open('{}/to_ignore.txt'.format(data_dir), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/dan_1/to_ignore.txt'
```

**Comment by 1p1pd** [comment]
Thank you for your interest in our work. You can now download the [sample data](https://drive.google.com/file/d/1kyNpmGKCYWZ46osHOA-WzW5HCNAcgDA1/view?usp=drive_link), and rerun the colab.

**Comment by SlimeVRX** [comment]
Thank you for the great work of the team. I will test with sample data
