### ISSUE TITLE
How to export texture?

### ISSUE THREAD

**Issue by SlimeVRX** [adobe-research/sunstage#3]
Thanks for your great work!

My goal: is to import highly detailed meshes and textures into 3D software like Blender, Unreal for rendering

How do export mesh and textures (diffuse, specular, normal)?

Like image

![image](https://github.com/RaduAlexandru/permuto_sdf/assets/99313947/1790faad-6ccb-4584-a8ca-aa63d95d0bf6)

**Comment by 1p1pd** [comment]
The mesh can be exported [here](https://github.com/adobe-research/sunstage/blob/main/sunstage_model_s2.py#L550) along with the [normal map](https://github.com/adobe-research/sunstage/blob/main/sunstage_model_s2.py#L577) available in both the UV and world space.

The diffuse albedo is [here](https://github.com/adobe-research/sunstage/blob/main/sunstage_model_s2.py#L576). You may need to apply a gamma to convert it from linear space to sRGB space. 

We used a Blinn-Phong model for the specular. The paramaters can be found [here](https://github.com/adobe-research/sunstage/blob/main/sunstage_model_s2.py#L654).

**Comment by SlimeVRX** [comment]
Thank you for the great work of the team! I'll try to get the texture (Normal Map, Diffuse Albedo, Specular)
